name: StockMLPipeline Automation

on:
  # Run every day at 10:30 AM IST (5:00 UTC)
  schedule:
    - cron: "0 5 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list  # ✅ Show installed packages for debugging

      # 4️⃣ Run the pipeline
      - name: Run StockMLPipeline
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: |
          echo "Running pipeline..."
          python src/auto_pipeline.py

      # 5️⃣ Commit & push generated reports (optional)
      - name: Commit and push reports
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reports/ || echo "No reports to add"
          git commit -m "Automated report update - $(date)" || echo "No changes to commit"
          git push || echo "No push required"
